#!/usr/bin/env python3

##
## EPITECH PROJECT, 2021
## B-MAT-400-MAR-4-1-208dowels-iliam.amara
## File description:
## 208dowels
##

import sys
import os

list_arg = list()

def error_management():
    global list_arg
    if len(sys.argv) != 10:
        return False
    i = 1
    try:
        while i != len(sys.argv):
            a = int(sys.argv[i])
            i += 1
    except:
        print("./208dowel: the {} arg wasn't a number".format(sys.argv[i]))
        return False
    i = 1
    list(list_arg)
    while i != len(sys.argv):
        list_arg.append(sys.argv[i])
        i += 1
    for d in list_arg:
        if (int(d) < 0):
            return False
    return True

def dowels():
    print("OK")
    
if __name__ == '__main__':
    if error_management() == False:
        sys.exit(84)
    else:
        dowels()