#!/usr/bin/env python3

##
## EPITECH PROJECT, 2021
## 207demography
## File description:
## 207demography
##

import os
import sys
import csv
from collections import OrderedDict

def help():
    print("USAGE")
    print("    ./207demography code [...]")
    print("\nDESCRIPTION")
    print("    code    country code")


def print_all():
    print("Country: {}".format(0))
    print("Fit1")
    print("\tY = {} X - {}".format(0, 0))
    print("\tRoot-mean-square deviation:{}".format(0))
    print("\tPopulation in 2050: {}".format(0))
    print("Fit2")
    print("\tX = {} Y + {}".format(0, 0))
    print("\tRoot-mean-square deviation: {}".format(0))
    print("\tPopulation in 2050: {}".format(0))
    print("Correlation: {}".format(0))

def make_dico(buffer):
    i = 1
    lcount = list()
    for key in buffer:
        while i != len(sys.argv):
            if key["Country Code"] == sys.argv[i]:
                lcount.append(key)
            i += 1
        i = 1
    return (lcount)

def add_name(list_count):
    name = str()
    if len(list_count) > 1:
        i = 0
        for line in list_count:
            if i == 0:
                name += line["Country Name"]
            else:
                name += ", " + line["Country Name"]
            i += 1
    else:
        for line in list_count:
            name += line["Country Name"]
    return name

def demography():
    global list_count
    global all_name
    try:
        sys.argv[1]
        if sys.argv[1] == "-h" or sys.argv[1] == "--help":
            help()
            sys.exit(0)
    except IndexError:
        sys.exit(84)
    buffer = csv.DictReader(open('207demography_data.csv'), delimiter=';')
    list_count = list()
    list_count = make_dico(buffer)
    if len(list_count) != (len(sys.argv) - 1):
        sys.exit(84)
    all_name = str()
    all_name = add_name(list_count)
    print(all_name)


if __name__ == '__main__':
    demography()